spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:filemanager
    password:
    name: demo-rizomm
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.H2Dialect

okta:
  oauth2:
    issuer: https://dev-765479.okta.com/oauth2/default
    clientId: 0oa21xb3r5McOuFCB357
